### ISSUE TITLE
Optimaliser is_TIHLDE_member

### ISSUE THREAD

**Issue by olros** [TIHLDE/Lepton#102]
Uthenting av brukere går veldig tregt så vi må gjøre noe med is_TIHLDE_member ettersom den genereres basert på mye nesting i sqlbog dermed fører til dårlig performance.

**Comment by Eirsteir** [comment]
Uten å ha sett for nøye på det, kunne det vært en idé å se nærmere på bruk av [cache](https://docs.djangoproject.com/en/3.2/topics/cache/) i Django

**Comment by olros** [comment]
Virket som det ikke var dette feltet som var problemet, men heller permissions
