### ISSUE TITLE
"Jeg ønsker ikke at bilde av meg skal bli tatt på event"-felt i user_event

### ISSUE THREAD

**Issue by Zenjjim** [tihlde/Lepton#116]
Legg til boolsk felt i user_event model som heter allow_image. Dette er default true. Dette må legges inn i serializer og view

**Comment by superspeed500** [comment]
Kaller feltet agree_photo istedenfor allow_image.

**Comment by olros** [comment]
`agree_photo` blir fremdeles ikke sendt ut i registration
