### ISSUE TITLE
Reset password peker til feil url

### ISSUE THREAD

**Issue by Eirsteir** [TIHLDE/Lepton#118]
Reset password prøver å ta brukeren til https://tihlde.org/api/v1/auth/reset/ZWlyc3RlaXI/alz0vh-8d0589ae8dc33879f88fe864db733dbd/, men det er ikke her api-et ligger lenger.

**Comment by Zenjjim** [comment]
haha skulle akk lage  den 😄

**Comment by Zenjjim** [comment]
skal peke til https://api.tihlde.org/api/v1/auth/reset/enVpbXJhbg/alz0zh-6e3b6874653d5f995afbfbcbd558feb8/

**Comment by Zenjjim** [comment]
nå peker den til https://tihlde.org//api/v1/auth/reset/enVpbXJhbg/alz0zh-6e3b6874653d5f995afbfbcbd558feb8/. legg merke til "//"        etter tihlde.org

**Comment by Eirsteir** [comment]
Endrer domenet i settings fra `tihlde.org/` til `api.tihlde.org` og tester litt lokalt 👍
