### ISSUE TITLE
Pages

### ISSUE THREAD

**Issue by Zenjjim** [tihlde/Lepton#123]
Lag en Wiki i likhet med Nyheter. Bruk tittel somo slug i urlen. 

- [x] Modell
- [x] Serializer
- [x] View

**Comment by Her0elt** [comment]
Tree struktur:
[https://django-mptt.readthedocs.io/en/latest/overview.html](url)
[https://django-treebeard.readthedocs.io/en/latest/](url)

**Comment by Her0elt** [comment]
Tree struktur:
[https://django-mptt.readthedocs.io/en/latest/overview.html](url)
[https://django-treebeard.readthedocs.io/en/latest/](url)
