### ISSUE TITLE
malicious URL-shortener

### ISSUE THREAD

**Issue by Zenjjim** [TIHLDE/Lepton#127]
Burde legge inn sjekk for at URLen ikke er "malicious". Dette kan gjøres med f.eks. [VirusTotal](https://developers.virustotal.com/v3.0/reference#overview ) som tilbyr et api for dette.

**Comment by olros** [comment]
Lagt inn en sanitizer av URL i Shorty:

https://github.com/TIHLDE/shorty/blob/d1155007b52f2473c4a15257c9c103238ec4ffe1/pages/%5B...slug%5D.tsx#L20

Dermed kan "malicious" URLs fremdeles opprettes, men de vil ikke bli vist til bruker.

Hvis det ikke er nok så er det bare å gjenåpne issuet :)
