### ISSUE TITLE
Implementere utestengning strike

### ISSUE THREAD

**Issue by Zenjjim** [TIHLDE/Lepton#137]
Utvidelse av #104 

Når evalueringsskjema er ordentlig implementert må det implementeres funksjonalitet for utestengning av all påmelding hvis man ikke svarer.

Forslag til løsning:
Lage en @task med celery som kjører 1 uke (?) etter eventslutt og hvis brukeren ikke har svart på eval skjema innen da skal de være utestengt fra alle arrangementer til skjemaet er svart på eller prikken går ut. 

Ved svar på skjema burde prikken bli slettet.

**Comment by Eirsteir** [comment]
Har man ikke svart på evalueringsskjemaet så kan man ikke melde seg på, punktum og implementert. Skal man få prikk for det også? 

Virker tungvint å la prikken bestemme dette, men en prikk vil også sørge for forsinket påmelding, så hvis den skal slettes når man svarer så har den i praksis ingenting å si - altså kan den sløyfes.

**Comment by Eirsteir** [comment]
Erstattet av #261
