### ISSUE TITLE
Filopplastning til Azure

### ISSUE THREAD

**Issue by Eirsteir** [TIHLDE/Lepton#14]
Som bruker på nettsiden ønsker jeg å kunne laste opp bilder og filer som kan brukes på nettsiden. Eksempler på hvor dette skal skje er profilbilde i profilen, filer i kokeboken og bilder til arrangementer, nyheter, karriere og pages.

**Comment by olros** [comment]
Det er ikke mulig å sende requests som inneholder både filer og JSON samtidig slik at man kan for eksempel ikke oppdetere et arrangement ved å sende både infoen om det og bildet dets i samme request.

Den beste løsningen da tror jeg er ved at Kvark først sender bildet til et eget endepunkt som kun tar i mot filer, laster de opp og returnerer en url man kan se filen på. Deretter sender Kvark en ny request som oppdeterer ressursen inkludert url'en til bildet.

Forslag til url der fil lastes opp er `/api/v1/upload/` som bør returnere noe sånt:
```json
{
  "url": "https://azure.com/folder/file.png"
}
```

Se TIHLDE/Kvark#24 for implementasjon i Kvark.
