### ISSUE TITLE
Oppgradere Python versjon til prosjektet til 3.9

### ISSUE THREAD

**Issue by Zenjjim** [TIHLDE/Lepton#151]
Nå begynner python å få mange nye gode funksjonaliteter og prosjektet begynner å henge mer og mer bak. Det er kanskje på tide å oppgradere python :D

**Comment by Eirsteir** [comment]
Latest stabel versjon er 3.9 så det kan være en idé å oppgradere til denne i stedet.

**Comment by olros** [comment]
Latest Django versjon (3.2.8) støtter opp til Python 3.9. Python 3.10 støtte kommer i Django 3.2.9 som kommer om ca en måned (https://docs.djangoproject.com/en/3.2/releases/3.2.9/). Oppdaterer dermed til 3.9 enn så lenge.

Ser forresten ut som Django 4 kommer rundt desember (https://docs.djangoproject.com/en/4.0/releases/4.0/) 🥳
