### ISSUE TITLE
Grupper

### ISSUE THREAD

**Issue by Eirsteir** [tihlde/Lepton#153]
Implementer egne grupper. En gruppe er enten en klasse (klasse og trinn), undergruppe, komité eller annen, for eksempel devkom, sosialen, hs ... , eller "år i dag" + studie (2019 data, 2020 digfor) osv. Den har et navn, en beskrivelse, og kontakt-epost. 

Videre skal HS kunne endre hvilken gruppe du er på. Det skal være mulig for alle å hente ut informasjon om grupper.

Oppgaven kan ses i sammenheng med at vi senere skal implementere medlemskap.

Gruppene kan hentes ut ved get_or_create(GROUP_NAME).

**Comment by Zenjjim** [comment]
- [ ] Lage en gruppe model: Group(<ins>group_slug</ins>, name, description, contact, type(UNDERGRUPPE, KOMMITE, KLASSETRINN, TIHLDE), permissions? (arve fra django_groups))
- [ ] Lage ulike serializers for ulike bruksområder. Her kan vi ha en diskusjon og finne ut av hvilken vi trenger
- [ ] Lage viewset for å hente ut groups, usikker på om vi trenger mulighet til endring av groups siden de er statiske og evt. endringer kan gjøres i admin panelet. Men er åpen for muligheten til å endre decription til en gruppe i nettsiden. Har du noen tanker her @olros

**Comment by olros** [comment]
Hvis vi for eks skal bruke disse gruppene til å vise undergrupper og komiteer på "Om TIHLDE" så kan det være lurt å kunne endre description. Vil gjøre det fryktelig mye enklere å holde de beskrivelsene oppdatert i allefall.

Spm: KLASSETRINN er det kun typ 2. klasse eller 2. klasse dataing? Og når man går opp ett trinn hver sommer, skal vi da fjerne folk fra en gruppe og legge de til i en annen, eller bare endre navn på gruppen?

**Comment by Zenjjim** [comment]
Det jeg tenkte iallefall er å ha år + studie. aka 2019 DataIng. Dette vil gjøre at vi slipper å øke klasse og vil automatisk fjerne folk når de går ut. Så kan vi heller ha litt backend magi som konverterer fra år til klasse.

**Comment by olros** [comment]
Høres lurt ut 👍

**Comment by Her0elt** [comment]
Group(Slug, name, Description, contact, TYPE(UNDERGRUPPE, KOMMITE, KLASSETRINN, TIHLDE)
Membership(ExpDate, User, Group, TYPE(member, leder), startdate)
