### ISSUE TITLE
Avslå nye brukere

### ISSUE THREAD

**Issue by olros** [TIHLDE/Lepton#154]
Som admin-bruker ønsker jeg å kunne avslå nye brukere. Dette fordi de enten ikke er medlem i TIHLDE, har ugyldig brukernavn, epost eller noe annet.

Bruker bør da slettes.

Det hadde også vært praktisk å kunne legge ved en begrunnelse som blir sendt på epost til person som prøvde å opprette bruker.

**Comment by treyshotz** [comment]
Legge til generiske/autogenererte begrunnelser så man slipper å skrive inn hver gang?

**Comment by olros** [comment]
> Legge til generiske/autogenererte begrunnelser så man slipper å skrive inn hver gang?

Kan legge det til i frontend ja, tenker vi i backend kun tar inn en "reason"-string
