### ISSUE TITLE
Gi tilbakemelding på alle requests

### ISSUE THREAD

**Issue by olros** [tihlde/Lepton#162]
Alle requests som backend mottar må svares på med JSON. Enten det opprettede/modifiserte objektet (for eksempel det nye eventet) eller med `detail: "Eventet ble slettet"`. Dette for å kunne vite om forespørsler har vært vellykkede i frontend og fordi frontend skal begynne å behandle alle svar om ikke inneholder JSON som mislykkede.

**Comment by Eirsteir** [comment]
Er denne helt ferdig @Her0elt ?

**Comment by Her0elt** [comment]
@Eirsteir ja er ganske sikker på det, spørsmålet er om @olros er fornøyd

**Comment by olros** [comment]
Tror vi får tilbakemelding overalt nå ja
