### ISSUE TITLE
Brukere kan ikke melde seg av arrangementer 

### ISSUE THREAD

**Issue by Eirsteir** [tihlde/Lepton#163]
Vanlig brukere kan ikke melde seg av arrangementer og får `403 FORBIDDEN` ved en DELETE HTTP request til userevent-endepunktet. Det kan virke som at problemet ligger i permissions for UserEventView og/eller i `delete` metoden.

**Comment by olros** [comment]
Det gjelder **alle** brukere, ikke bare alumni. Vi har ikke oppdaget det fordi vi er _superusers_
