### ISSUE TITLE
[Refactor]: overwrite med ny submission hvis ikke tilknyttet event

### ISSUE THREAD

**Issue by olros** [TIHLDE/Lepton#176]
Per nå er det ikke mulig å opprette flere EventSurveySubmissions til samme form for en bruker. Det er riktig så lenge brukeren også er påmeldt arrangementet.

Problemet oppstår om brukeren oppretter en submission, men av en eller annen grunn ikke blir påmeldt (nettverket faller ut for eks.). Da må det være mulig å sende inn en ny submission i sammenheng med nytt påmeldingsforsøk. Alternativet for frontend er å sende en request som sjekker om submission allerede er sendt inn og isåfall enten ikke vise spørsmålene eller å slette submission før påmelding. Dette er tungvint og etter min mening ikke særlig optimalt.

**Comment by Eirsteir** [comment]
En ting vi også må tenke på her er at Forms og Submission skal være generelt og kunne brukes til andre ting som nyheter osv. Likevel er det såpass mye forretningslogikk knyttet til akkurat påmelding og det bør her være mulig å gjenbruke det meste av logikken vi allerede har laget.

**Comment by olros** [comment]
Forslag:

Tillat ny POST til `forms/<form-id>/submissions/`  når submission på `form-id` og `user` allerede eksisterer, hvis og bare hvis:
```python
if submission.form.type == 'event_survey' and not user in submission.form.event.registrations
```
