### ISSUE TITLE
Swagger krasjer pga /statistics

### ISSUE THREAD

**Issue by olros** [TIHLDE/Lepton#192]
Etter at form-statistics kom inn krasjer Swagger.

![image](https://user-images.githubusercontent.com/31009729/132888496-750d1b5e-31f9-4981-8782-8119f2ed818f.png)

*Reproduser*:
- Åpne `http://localhost:8000/api/` / `https://api-dev.tihlde.org/api/`

*"Fiks"*:
- Kommenter ut linjen med `router.register(r"(?P<form_id>[0-9a-f-]+)/statistics", StatisticsViewSet)` i `app\forms\urls.py`

Feilmelding:
![image](https://user-images.githubusercontent.com/31009729/132888331-6eb2c4ef-58df-41d8-b528-45c768498798.png)

Testet [dette](https://drf-yasg.readthedocs.io/en/stable/custom_spec.html#support-for-serializermethodfield) men fikk det ikke til å fikse feilen.

**Comment by Eirsteir** [comment]
Ser ut som et problem med `statistics = SerializerMethodField()` i `FormStatisticsSerializer`, hvis man kommenterer ut denne og i `Meta.fields` så fungerer det
