### ISSUE TITLE
Umiddelbar brukerregistrering uten godkjennelse / Forsinket godkjennelse

### ISSUE THREAD

**Issue by Eirsteir** [TIHLDE/Lepton#203]
**Use-case:** Som besøkende ønsker jeg å kunne lage en bruker uten å måtte vente på å bli godkjent som medlem slik at jeg kan logge inn å ta i bruk siden.

Det er mye forvirring og venting knyttet til å måtte bli godkjent som medlem før man kan logge inn. Dette bør endres slik at man kan logge inn med en gang, uten tilgang til det et vanlig medlem har tilgang til. 

Hypotesen er at dette vil føre til en bedre brukeropplevelse og et bedre førsteinntrykk av både TIHLDE og nettsiden.

**Comment by thomsen85** [comment]
Ble lagt på is, pga. ser heller på bedre måter med autentisering
