### ISSUE TITLE
Avsender-navn i eposter

### ISSUE THREAD

**Issue by olros** [TIHLDE/Lepton#208]
Når man mottar epost fra oss nå så står det (i hvertfsll hos Gmail) "no-reply" som navn på avsender. Regner med at det er fordi vi sender fra `no-reply@tihlde.org`. Regner også med at vi kan sette dette navnet selv på en eller annen måte slik at det står TIHLDE istedenfor.

Kan sees i sammenheng med #170

**Comment by Eirsteir** [comment]
Jeg har prøvd å endre avsendernavn i gmail-kontoen uten hell, men vet ikke om det kan gjøres programmatisk. Ser gjerne på det sammen en dag :)

**Comment by olros** [comment]
Tror dette bør funke: https://docs.djangoproject.com/en/3.2/topics/email/#django.core.mail.EmailMessage

```
from_email: The sender’s address. Both fred@example.com and "Fred" <fred@example.com> forms are legal.
```

https://stackoverflow.com/a/2112818

**Comment by olros** [comment]
I tillegg bør vi kanskje se på `send_mass_mail()` for å øke farten når vi sender ut mange eposter: https://docs.djangoproject.com/en/3.2/topics/email/#send-mass-mail

**Comment by Eirsteir** [comment]
Støttes!

**Comment by Eirsteir** [comment]
Kan også sette inn en default avsender: https://docs.djangoproject.com/en/dev/ref/settings/#default-from-email
