### ISSUE TITLE
Default mail

### ISSUE THREAD

**Issue by Zenjjim** [tihlde/Lepton#223]
Mail blir sendt fra no-reply-devkom@tihlde.org. Dette burde byttes til no-reply@tihlde.org og burde ikke tilhøre noen undergruppe. Ikke NOK ikke Index, ingen.

**Comment by Eirsteir** [comment]
Ligger denne mailen som en miljøvariabel i prod?

**Comment by Eirsteir** [comment]
Oppdatert hos Drift
