### ISSUE TITLE
Håndter StrikeErrors så det ikke blir logget til sentry

### ISSUE THREAD

**Issue by Eirsteir** [TIHLDE/Lepton#226]
StrikeErrors blir hevet for å hindre at noen med prikker melder seg på uten de restriksjonene som medfølger prikkene. Dette er riktig, men ikke en "feil" i API'et og bør derfor ikke logges til sentry.

Se hendelsen på sentry her: https://sentry.io/share/issue/2dad3810fe874a5fba74aff49d77bd59/

**Comment by Eirsteir** [comment]
Meldingen som returneres ved 500 Internal Server Error har altså forbedringspotensiale.

**Comment by olros** [comment]
Ooh ja, i tillegg til å håndtere en evt StrikeException ved påmelding så kan vi håndtere 500 Internal Server Error slik at vi kan sende en JSON-repons også da: https://stackoverflow.com/questions/60494412/handle-500-internal-error-in-django-rest-framework. Da vil bruker faktisk få opp en snackbar der det kan stå noe a la "Noe gikk helt galt, kontakt TIHLDE Index for hjelp"

**Comment by Eirsteir** [comment]
Det er en clean måte å løse det på 🌟 Mener vi også kan håndtere det her: https://github.com/TIHLDE/Lepton/blob/dev/app/util/exceptions.py

**Comment by olros** [comment]
God mulighet det og ja.

**For å reprodusere feilen**:
1. Lag en strike på brukeren din
2. Prøv å meld deg på et arrangement
