### ISSUE TITLE
Flytt opp påmeldte fra ventelisten selv når det ikke er noen prioriterte på denne

### ISSUE THREAD

**Issue by Eirsteir** [tihlde/Lepton#230]
Når det ikke er noen prioriterte på ventelisten og noen melder seg av, blir ingen flyttet opp. Her er det ønskelig at den av de på ventelisten som meldte seg på først blir flyttet opp.

**Comment by Zenjjim** [comment]
![Screenshot_20210112-085500.jpg](https://user-images.githubusercontent.com/23628986/104285421-e2730500-54b3-11eb-9685-9bf3f53836c5.jpg)
Er det en bug i denne testen da?

**Comment by Eirsteir** [comment]
Nei, men forskjellen er at i denne buggen så har eventet en eller flere prioriteringer, men ingen på ventelisten tilhører noen av dem. Slik at hvis du har akkurat samme test som den der, men legger til en prioritering på eventet som ingen av brukerne tilhører så vil du reprodusere buggen.

**Comment by Eirsteir** [comment]
Nei, men forskjellen er at i denne buggen så har eventet en eller flere prioriteringer, men ingen på ventelisten tilhører noen av dem. Slik at hvis du har akkurat samme test som den der, men legger til en prioritering på eventet som ingen av brukerne tilhører så vil du reprodusere buggen.

**Comment by Zenjjim** [comment]
![image](https://user-images.githubusercontent.com/23628986/104843386-a9c79700-58ca-11eb-8608-19ec578b5838.png)
Men da ligger buggen antaglig i denne kodesnutten. Den skal i prinsippet sjekke om det er noen registrerte i for-loopen. Hvis ikke velger den bare den første fra listen.

**Comment by Zenjjim** [comment]
Jeg fant buggen. Når man avmelder seg som admin, blir ikke den orginale move_up funksjonen kjørt, siden vi ikke ønsker det skal skje når admin flytter andre. Så måten vi fikser det er ved å sjekke om brukeren er  admin og ikke  fjerner seg selv
