### ISSUE TITLE
Ikke gi prikk til alle på ventelisten for å ikke ha møtt

### ISSUE THREAD

**Issue by Eirsteir** [TIHLDE/Lepton#243]
Per nå gis det prikker automagisk til _alle_ som har en Registration til et arrangement som ikke har møtt, inklusiv de på ventelisten. Siden de på ventelisten ikke hadde plass på arrangementet og har følgelig ikke ankommet/møtt, skal de heller ikke få prikk for dette. 

Endre derfor på [denne celery-tasken](https://github.com/TIHLDE/Lepton/blob/1078844b5de9d45a91a4450cc224a3f378514f85/app/content/tasks/event.py#L14) som er ansvarlig for å dele ut prikker i denne sammenheng.

**Comment by olros** [comment]
Skulle blitt lukket av #246
