### ISSUE TITLE
Fjern fullt navn til de påmeldte fra responsen til arrangementer 

### ISSUE THREAD

**Issue by Eirsteir** [tihlde/Lepton#244]
Fullt navn på de påmeldte brukerne skal ikke sendes med i responsen når vi henter ut events (https://tihlde.org/api/v1/events/), kun `user_id`.

**Comment by olros** [comment]
Ser ikke noe grunn til at `user_id` skal med heller, så vidt jeg vet brukes ikke `registered_users_list` i det hele tatt. Feltene i hvert event når man henter flere bør også reduseres til de som er i bruk.

**Comment by Eirsteir** [comment]
Hvis det ikke brukes så fjerner vi det. Er det heller ikke behov for `registered_users_list` når man henter ut ett event?

**Comment by olros** [comment]
Nei, vi henter ut påmeldte gjennom `event/id/registrations/`

**Comment by Eirsteir** [comment]
Lukker grunnet #248
