### ISSUE TITLE
Print alle felt i __str__ i models for bedre logs

### ISSUE THREAD

**Issue by olros** [TIHLDE/Lepton#247]
Det er vanskelig å se hva som har blitt endret i loggen nå. Hvis man legger til alle feltene i objektet i `__str__` så vil man kunne sammenligne lettere i loggen nøyaktig hva i modellen som har blitt endret fra gang til gang.

TODO:
- [ ] Legg til alle modellens felter i `__str__` i alle modeller

**Comment by Eirsteir** [comment]
Husk at `__str__` brukes av Django i adminpanelet for å vise frem listene, så det kan være en idé å heller overskrive `__repr__` og bruke denne.

Dette bør også legges inn som en Mixin-klasse for modellene så slipper man å definere en for hver modell.

**Comment by olros** [comment]
Dette er rettet i #390
