### ISSUE TITLE
Logg opprettelse og sletting av objekter

### ISSUE THREAD

**Issue by olros** [TIHLDE/Lepton#251]
Per nå logges det ikke opprettelse og sletting av objekter/modeller. Dette bør også logges for å skape mer fullstendige logger

**Comment by Eirsteir** [comment]
Tenker du på objekter som ikke blir opprettet/slettet gjennom en `BaseSerializer`?

**Comment by olros** [comment]
Vet ikke hvorfor men det blir ikke opprettet logginnlegg når det opprettes events, news, pages, jobposts, osv... Mistenker det er fordi det kun logges når instansen har en pk og at pk ikke er satt når funksjonen kjøres:

https://github.dev/TIHLDE/Lepton/blob/6a2d7b32471e49e3d3156889d6acfe2e79cb48ec/app/common/serializers.py#L17-L17

I tillegg er det heller ikke funksjon for `destroy` der

**Comment by olros** [comment]
Dette er gjort i #390
