### ISSUE TITLE
La brukere på venteliste melde seg av etter avmeldingsfrist

### ISSUE THREAD

**Issue by trthingnes** [tihlde/Lepton#254]
We should consider letting people cancel events if they get moved to the waitlist after the deadline. Since if you sign up, then get a message about being moved to the waitlist after the cancellation deadline, you can do nothing else during the event time without risking getting a prikk.

Example:
User signs up, gets booted the day before the event, cannot plan to do something else instead since they risk getting back into the event after making other plans. Therefore they need to keep their schedule clear even though they probably will not be allowed in the event.

**Comment by olros** [comment]
NoK er enige og vi kan da endre til å la brukere på ventelisten melde seg av også **etter** avmeldingsfristen
