### ISSUE TITLE
20 dager utestenging ved ubesvart evaluering

### ISSUE THREAD

**Issue by Eirsteir** [TIHLDE/Lepton#261]
**Som arrangør ønsker jeg ikke at brukere med prikker pga ubesvarte evalueringsskjemaer skal kunne melde seg på nye arrangementer i 20 dager etter arrangementsslutt, slik at jeg vi følger arrangementsreglene**

**Comment by olros** [comment]
Hvis jeg tolker denne rett så er ikke prikker relevant her. Det som skal gjøres er at brukere ikke skal kunne melde seg på et arrangement så lenge de har en ubesvart evalueringsskjema som er knyttet til et arrangement som ble avsluttet for mindre enn 20 dager siden.

Her må det også tenkes på hvordan frontend skal vite om man kan melde seg på eller ikke basert på `viewer_has_unanswered_forms`. Den må også være false hvis det har gått mer enn 20 dager
