### ISSUE TITLE
Send varsler til Facebook Messenger

### ISSUE THREAD

**Issue by olros** [TIHLDE/Lepton#29]
Facebook Messenger har et api som gjør det mulig å blant annet sende meldinger til brukere med oppdateringer om arrangementer brukeren er påmeldt. Det vil kunne brukes ved siden av/istedenfor eposter. Bør nok i tillegg ha innstillinger der bruker kan velge hvor han vil motta varsler: epost/messenger/etc..

https://developers.facebook.com/docs/messenger-platform/send-messages/message-tags

*"Message Tags enable businesses to send important and personally relevant 1:1 updates to users outside the 24 hour Standard messaging window for a set of approved use cases. For example, you may send updates about shipping and delivery, an upcoming reservation or flight, or alerts about a customer’s account."*

https://developers.facebook.com/docs/messenger-platform/discovery/checkbox-plugin

**Comment by thomsen85** [comment]
No longer relevant, wishing more for push notifications directly from site.
