### ISSUE TITLE
Badges ledertavle

### ISSUE THREAD

**Issue by olros** [TIHLDE/Lepton#306]
Som medlem i TIHLDE ønsker jeg å se hvem som har flest badges totalt sett, hvem som har flest badges per årstrinn og hvem som har et spesifikt badge. Dette bør kun være tilgjengelig for innloggede medlemmer. Man trenger her endepunkter for de forskjellige listene, eller at det gjøres gjennom et BadgesFilter

**Comment by CJGutz** [comment]
I hvilket format vil for eksempel endepunktet for hvem som har flest badges være i? Noe som dette?
```
{
     { "user_id": "brukernavn", "antall_badges":"tall" },
     { "user_id": "brukernavn", "antall_badges":"tall" }
}
```
eller noe rundt dette?
```
{
   { "User": "bruker", "badges": { "badge": "en badge", "badge": "en annen badge", "badge": "en tredje badge" } }
   { "User": "bruker", "badges": { "badge": "en badge", "badge": "en annen badge", "badge": "en tredje badge" } }
}
```
eller noe helt annet?

**Comment by olros** [comment]
> I hvilket format vil for eksempel endepunktet for hvem som har flest badges være i? Noe som dette?
> 
> ```
> {
>      { "user_id": "brukernavn", "antall_badges":"tall" },
>      { "user_id": "brukernavn", "antall_badges":"tall" }
> }
> ```
> 
> eller noe rundt dette?
> 
> ```
> {
>    { "User": "bruker", "badges": { "badge": "en badge", "badge": "en annen badge", "badge": "en tredje badge" } }
>    { "User": "bruker", "badges": { "badge": "en badge", "badge": "en annen badge", "badge": "en tredje badge" } }
> }
> ```
> 
> eller noe helt annet?

Har egentlig ikke tenkt så langt. Det vi må tenke på er hva som er relevant å vise frem på nettsiden. Skal vi vise kun antall eller også hvilke spesifikke badges akkurat som de 2 alternativene dine. Tenker flere/noen på frontend bør være med på den diskusjonen

**Comment by CJGutz** [comment]
Ok da tar jeg kodingen av det litt på vent

**Comment by olros** [comment]
# Visjon for badges ledertavler

Litt tanker om hva jeg tror hadde vært kult med ledertavlene og hvilke vi bør ha

## 1 Modeller

### 1.1 Start- og sluttidspunkt på badges

- Som administrator ønsker jeg å kunne si hvilket spesifikt tidsrom det skal være mulig å få en badge. For eksempel skal et "Påskebadge" kun være mulig å få en spesifikk påske.
- Dette er viktig for å hindre at brukere finner `id` på et badge lenge etter at det var mulig å finne for eks gjennom en CTF, og da får det selv gjennom å sende en POST-request til `api.tihlde.org/badge/` eller fyller det inn i input på forsiden når det er synlig. Sannsynligheten for at dette skjer blir mye større når brukerne får tilgang til en oversikt over alle badges.

Legg til i modell: ``badge`

```
active_from: Date (nullable)
active_to: Date (nullable)
```

Hvis begge er `null` så kan man alltid få en `user_badge`. Hvis `active_from` er `null` så kan man få `user_badge` frem til `active_to`. Hvis `active_to` er `null` så kan man få `user_badge` etter `active_from`. Hvis ingen er `null` kan man kun få `user_badge` mellom `active_from` og `active_to`.

### 1.2 Badge kategorier

- Med så mange badges på siden er det nyttig å kunne kategorisere dem, særlig når vi har CTF eller lignende. Gjennom kategorisering vil man kunne se en ledertavle for en spesifikk CTF for eksempel.

Ny modell: `badge_category`

```
id: Uuid
name: CharField
description: TextField (default="", blank=True)
image: CharField
image_alt: CharField
```

Legg til i modell: ``badge`

```
category: BadgeCategory (nullable)
```

## 2 Endepunkter

### 2.1 Flest bagdes totalt

- Som bruker ønsker jeg å se en totaloversikt over hvem som har flest badges.
  - Dette kan legges under endepunktet: GET `api.tihlde.org/badges/leaderboard/`
- Som bruker ønsker jeg også å kunne filtrere dette på årstrinn og klassetrinn slik at jeg kan sammenligne meg selv mot en spesifikk gruppe.
  - Dette kan legges under endepunktet: GET `api.tihlde.org/badges/leaderboard/?user_class=2&user_study=Dataing`
- *Dette kan sorteres på antall badges brukeren har totalt by default. Ser ikke behov for at denne sorteringen skal kunne endres fra frontend heller.*

Returformat: (pagination)

```json
{
  "count": 1,
  "next": null,
  "previous": null,
  "results": [
    {
      "user": {
        "user_id": "olafros",
        "first_name": "Olaf",
        "last_name": "Rosendahl",
        "image": "",
      },
      "number_of_strikes": 18,
    }
  ]
}
```

### 2.2 Hvem har en spesifikk badge

- Som bruker ønsker jeg å se hvem som har en spesifikk badge
  - Dette kan legges under endepunktet: GET `api.tihlde.org/badges/<id>/leaderboard/`
    - Her kan det returneres pagination sortert på når brukeren fikk badgen.
  - For at dette skal være mulig må også endepunktet for å se alle badges åpnes opp: GET `api.tihlde.org/badges/` -> Returner pagination slik som i GET `api.tihlde.org/user/me/badges/` i dag.
  - For at dette skal være mulig må også endepunktet for å hente en spesifikk badge åpnes opp: GET `api.tihlde.org/badges/<id>/`

Returformat: (pagination)

```json
{
  "count": 1,
  "next": null,
  "previous": null,
  "results": [
    {
      "user": {
        "user_id": "olafros",
        "first_name": "Olaf",
        "last_name": "Rosendahl",
        "image": "",
      },
      "created_at": "2021-10-27T20:00:00+01:00",
    }
  ]
}
```

### 2.3 Flest badges i kategori

- Som bruker ønsker jeg å se hvem som har flest badges i for eksempel CTF høsten 2021. For at dette skal bli mulig må vi bruke `badge_category`-modellen som beskrevet i "1.2".
  - Dette kan legges under endepunktet: GET `api.tihlde.org/badges/leaderboard/?category=<uuid>`
  - Hvis du har fulgt med hit så ser du sikkert at det er samme endepunkt som i punkt **1**. Det vil bety at man skal kunne filtere på klassetrinn og studie også her. Alt kan altså legges på samme endepunkt.

Returformat her kan være likt det i punkt **1**.

### 2.4 En spesifikk brukes badges

- Som bruker ønsker jeg å se hvilke badges en spesifikk bruker har. I frontend er dette nyttig enten om vi skal vise det rett fra ledertavlen eller i offentlige profiler (#324) som kommer.
  - Dette kan legges under endepunktet: GET `api.tihlde.org/user/<user_id>/badges/` og returnere på akkurat samme format som GET `api.tihlde.org/user/me/badges/` gjør i dag. Det bør også være mulig å kombinere disse to endepunktene til 1 `@Action` i UserViewSet.

**Comment by CJGutz** [comment]
@olros skal jeg kanskje bruker endepunktnavn "badge/" istedenfor "badges/". Det følger det nåværende navngivningen til andre endepunkter. Eneste problemet blir da hva som skal skje med det nåværende endepunktet "badge/" som går til UserBadgeViewSet. Tenker det beste er å endre den til "user-badge/"

**Comment by olros** [comment]
Jeg synes det skal endres til "badges/", det er vanlig praksis med flertalls-navngivning i REST (bare søk på "REST api singular vs plural"). Er bare vi som ikke har være flinke på å standardisere det.

Tenker UserBadgeViewSet kan legges på `api.tihlde.org/badges/<badge_id>/users/`

**Comment by CJGutz** [comment]
Et nytt problem som kommer opp er jo at Badges som skal være hemmelige gjennom en CTF for eksempel vil være synlig på en buker sin offentlige profil. En løsning, som kanskje er den beste er å bare vise badges som enten ikke har en active_to dato eller har passert sin active_to dato. Da kommer det opp et nytt spørsmål om hvilke badges som skal telles i number_of_badges. Skal alle badges inkludert de som blir ekskludert telles eller bare de man kan se på en profil. Beste er å bare telle de som er på profilen, så en person ikke kan se at en profil har en hemmelig badge.

**Comment by olros** [comment]
Et annet alternativ er at vi lager 2 id'er for hver badge. 1 som bruker for å liste det opp og se ledertavlen dens på en url, også 1 som brukes for å få det gjennom et flagg. Da vil man kunne viste frem badges uten at man får id'en til badget og dermed kan få det selv så enkelt.

Problemet er fremdeles som du sier hvis det er et badge man ikke ønsker at skal kunne sees før man har funnet det eller active_to har passert. Hva tror dere @trthingnes @Her0elt , er det mange badges der det vil være et problem at man kan se det uten å ha funnet det selv?

**Comment by CJGutz** [comment]
### Det er 4 steder badges vises eller telles:

1. Liste over alle badges. På urlen `/badges/`. Viser alle badges.
2. Hoved leaderboard- På urlen `/badges/leaderboard/`. Viser bruker og antall badges.
3. Badge-spesifikk leaderboard. På urlen `/badges/<badge_id>/leaderboard/`. Viser bruker og datoen badgen ble tatt.
4. Offentlig profil. På urlen `/user/<user_id eller me>/badges/`. Viser alle detaljerte badges for en bruker

### Dette kan være mulige løsninger. Tallene korresponderer:

1. Medlemmer burde ikke vite om hvilke badges eksisterer. Derfor burde denne urlen bare være tilgjengelig til **HS** og **Index**.
Selv om vi filtrerer på bare public badges (hvor enten **active_to** er passert eller **active_to** er null og **active_from** er passert), vil badges som alltid er active bli lettere funnet ved å for eksempel se på beskrivelsen. Jeg har lagt til en queryset expression for å filtrere public badges, men vurderer å droppe dette.
2. Om man ignorerer om badges er **offentlige**, vil det være mulig å se når medlemmer har fått en badge og hvem som holder på vinne for eksempel en CTF. Tenker likevel at dette ikke er problem med tanke på at id-en til badgen ikke vises. Kanskje det til og med lager større insentiv ettersom folk får konkurranseinstinkt av å se at noen har skaffet en til badge.
3. Ettersom man bare får tilgang til denne ved å ha id-en må man ha funnet badgen uansett. For eksempel kan man komme til urlen via egen profil ved å trykke på en badge man har **oppnådd**. Eventuelt kan man trykke på en annen profil sine badger og komme til en ledertavle man ikke har nådd selv, mener **offentlig**. Om tilfelle er som det sistnevnte, kan man ha to id'er som du nevnte.
4. Her er det nok best med **offentlige** badges i tillegg til badges som brukeren, altså brukeren som ser på profilen, har skaffet.  Om badge-spesifikk ledertavle bare skal vises til brukere som har selve badgen, får det være slik på en **offentlig** profil også.
Tenker at **offentlige** og **oppnådde** badges vises på profilen så får man sett en ledertavle for en badge man selv ikke har.

Om vi bruker idéen om **offentlige** badges, vil badges fra CTF-er og lignende uansett ikke vises til brukere før et medlem enten har **oppnådd** badgen eller **active_to** datoen er passert. Altså blir det ikke et problem for konkurranser hvor badger har en satt **active_to** dato. Det er disse badgene som man ikke ønsker skal vises før konkurransen er ferdig. For Rick Roll badgen og andre badger der **active_to** ikker definert er det nok greit om man ser badgen på en profil uten å kunne finne id med en gang.

**Comment by Zenjjim** [comment]
Hei, liten ide mtp CTF. Om badges beholder konseptet om en uuid men også har et `flag` felt hvor jeg kan skrive hva som helst. f.eks. "tihlde_hemmelig_ctf_flag" hadde dette vært meget gunstig. Så kan man heller bruke disse flaggene til å få claimet CTF flagget og få badgen. Da kan dere sende id til frontend så mye dere vil og "flag" beholdes i backend :shipit:

**Comment by olros** [comment]
> Hei, liten ide mtp CTF. Om badges beholder konseptet om en uuid men også har et `flag` felt hvor jeg kan skrive hva som helst. f.eks. "tihlde_hemmelig_ctf_flag" hadde dette vært meget gunstig. Så kan man heller bruke disse flaggene til å få claimet CTF flagget og få badgen. Da kan dere sende id til frontend så mye dere vil og "flag" beholdes i backend :shipit:

Noe a la dette jeg prøvde å foreslå litt opp. Da kan vi sende badges hvor som helst uten å være redd for at brukere skal finne flagget. Så kan vi bruke offentlig-teknikken som du har jobbet med @CJGutz

**Comment by CJGutz** [comment]
Ja to ideer, eller en id og et valgfritt flag, blir nok nødvendig. Skal vi sende POST requesten gjennom `/users/zuimran/badges/`. Det kan absolutt fungere så sender man bare flagget i request dataen. Hvis ikke blir det å sende POST gjennom `/badges/<badge_id>/users/` eller `/badges/users/`. Er det bedre å bruke den første om en bruker sender flagget fra profilen?. Har også gjort det slik at hvis flagget ikke er skrevet inn, blir det satt til ide-en.

**Comment by Zenjjim** [comment]
Her er jo spørsmålet om hva du definerer som en eier. Er det `user` som eier `badge` eller `badge` som eier `user`. Er jo selvfølgelig mulig å gå begge veier men REST handler om å hente ressurser basert på eier. Personlig så vil jeg anta at `POST: /badges/<badge_id>/users/` oppretter en bruker til badge med id `<badge_id>`. Endepunktet `POST: /badges/users` antar jeg at det opprettes en bruker til badges (som kanskje ikke helt gir mening 🤷🏾).  

Derimot så ville jeg foreslått `POST: /users/<user_id>/badges/` som i mitt hode lager en badge til bruker med id: `<user_id>` . Da passer vi både på at vi opprettholder bruker som eier av en badge, som i mitt hode gir mest mening.

PS: det er antatt at ressurser som ikke er oppgitt i URI er definert i `body`.
- For `/badges/<badge_id>/users/` vil dette være user_id
- For `/badges/users` vil dette være både være user_id og badge_id
- For `/users/<user_id>/badges/` vil dette være badge_id

Kom gjerne med kommentarer for dette er bare et forslag fra min side.

**Comment by CJGutz** [comment]
Jeg liker forslaget veldig gått. Da lager jeg en @action metode i UserViewSet og lager en funksjon av UserBadgeViewSet med  UserBadgeViewSet.as_view(post:create)
