### ISSUE TITLE
Undersøk det at påmeldte får flere like mails/notifikasjoner om gangen 

### ISSUE THREAD

**Issue by Eirsteir** [TIHLDE/Lepton#31]
Det hender ofte at de påmeldte får den samme mailen flere ganger og det kan virke som at det er en bug i mailer-logikken vår. Dette må undersøkes.

**Comment by Zenjjim** [comment]
Så har sittet og gravd litt i Abakus-Lego og sett på måten de løser celery (cron-job).
Litt info for de som ikke vet, måten vi løser celery slik (kun for ting som er dato basert, avmeldings påminnelse, evalueringsskjema etter event osv):
1. Når et event blir opprettet blir det laget en oppgave/funksjon som skal sende ut notifikasjon ved gitt dato. Denne oppgaven sendes til RabbitMQ for lagring, og oppgavens id lagres i databasen (under event)
2. Når denne datoen+tidspunket inntreffer blir oppgaven sendt tilbake til celery/vår backend for å kjøre funksjonen.
Dersom et event blir oppdatert må denne oppgaven oppdateres, som betyr at oppgaven i RabbitMQ på slettes, og en ny en må lages. Dette betyr at man bruker Iden i databasen, bruker denne til å slette oppgaven og lage ny oppgave og oppdatere iden i databasen.
Måten Lego gjør dette på er at de har et objekt med ulike "scheduled" oppgaver som har egen crontab.
eks:
```
schedule = {
    "check-for-bump-after-penalty-expiration": {
        "task": "lego.apps.events.tasks.check_events_for_registrations_with_expired_penalties",
        "schedule": crontab(minute="*/5"),
    },
    "notify_event_creator_when_payment_overdue": {
        "task": "lego.apps.events.tasks.notify_event_creator_when_payment_overdue",
        "schedule": crontab(hour=9, minute=0),
    }
}
```
Så istedenfor å planlegge en spesifikk oppgave som kjører på gitt dato, har de en oppgave som kjører en gang hvert 5 min, hvert 9 time osv.
Fordelen med dette er at man slipper å lagre iden til cron-oppgaven og slipper å konstant oppdatere oppgaven i rabbitMQ. Ulempen er at det er oppgaver som kjører hele tiden og og jeg er litt usikker på hvordan de sjekker at tasken har kjørt, men det ser ut som de har has_sent verdi på survey, pool og andre objekter som sender ut notifikasjon.
Spørsmålet mitt da og det som er greit å få diskutert er hva mener dere er en bedre løsning å gå for, fordi jeg personlig mener at det er tyngre å ha en ekstra ID i event for oppgaven og å måtte konstant oppdatere denne. I tillegg er det ingen sikkerhet at dersom cron feiler er det ingen sikring om den vil kjøre igjen. Lego sin løsning vil være mer robust siden den kjører uavhenigig av endinger i event og i rabbitMQ.
