### ISSUE TITLE
Bruk factories istedenfor fixtures for dummy-data

### ISSUE THREAD

**Issue by Eirsteir** [TIHLDE/Lepton#322]
Fixtures må vedlikeholdes og oppdateres hver gang vi gjør endringer på modeller som igjen fører til at det ofte breaker. Det er derfor lurt å lage såkalte Management commands for å "seede" databasen med ønsket og random data. Her kan man da lage en batch med 10-20-50-100 objekter som lagres med random data. Vi vil også da få mer realistiske testdata og merker lokalt hvis noe er særdeles treigt med mye data.

**Comment by olros** [comment]
🙌🙌🙌
