### ISSUE TITLE
Permissions  cache fører til gammel data på brukere

### ISSUE THREAD

**Issue by Her0elt** [TIHLDE/Lepton#333]
Cachen på permissions gjør at hvis du oppdaterer brukeren din så vil ikke endringene vises

![image](https://user-images.githubusercontent.com/60223374/141536337-e6bc0db7-f13b-414d-8da6-3a024eea0d8f.png)
![image](https://user-images.githubusercontent.com/60223374/141536362-e7b964b0-f881-4c46-a4c9-bf1a4dbca731.png)

**Comment by olros** [comment]
Dette er fikset gjennom #414
