### ISSUE TITLE
Kommentarer på innlegg

### ISSUE THREAD

**Issue by trthingnes** [TIHLDE/Lepton#356]
Legg inn støtte for kommentarer på innlegg.

Som redaktør ønsker jeg å kunne slå av og på kommentarfeltet på nyhetssaker.
Som redaktør ønsker jeg å kunne moderere kommentarfeltet.

Som bruker ønsker jeg å kunne legge inn kommentarer på innlegg.

**Comment by thomsen85** [comment]
Med innlegg, menes det da bare nyheter eller også arrangementer og karriere innlegg?
