### ISSUE TITLE
Slett bruker

### ISSUE THREAD

**Issue by olros** [TIHLDE/Lepton#368]
Som administrator (kun Index-medlem) ønsker jeg å kunne slette brukere. Dette kan være etter ønske (GDPR), eller for eksempel brukere som ikke er medlem. Dette trenger ikke være tilgjengelig på et endepunkt, det bør holde å kunne gjøre det gjennom Django-adminpanelet.

Ikke mulig i dag fordi man ikke har mulighet til å slette logginnlegg som er koblet til brukere, superusers bør få tilgang til det.

Det må også dobbelsjekkes at ingen andre objekter slettes gjennom cascade som ikke skal slettes.

**Comment by Her0elt** [comment]
https://blog.eleni.co/gdpr-django-collector/
