### ISSUE TITLE
Mail ved interesse for annonse

### ISSUE THREAD

**Issue by olros** [TIHLDE/Lepton#380]
### Feature request

Endre slik at alle som kontakter oss på nettsiden angående kun stillingsannonse blir sendt direkte til stillingsannonser@tihlde.org istedenfor naeringslivminister@tihlde.org?

**Comment by Her0elt** [comment]
Blir ikke dette bare en env change i azure

**Comment by olros** [comment]
Nei, for interesse for arrangementer skal fremdeles gå til naeringslivminister@tihlde.org.

**Comment by Her0elt** [comment]
Ah da så
