### ISSUE TITLE
Offentlig uthenting av grupper med filtrering

### ISSUE THREAD

**Issue by Eirsteir** [TIHLDE/Lepton#490]
Vi trenger et endepunkt hvor alle kan hente ut grupper med filtrering som kan brukes bla ved #483 og prioritetspools. Endepunktet må støtte filtrering på gruppetypen. 

Ref denne diskusjonen: 
> Så jeg husker: vi må ha en måte for alle å hente ut alle grupper for å kunne velge grupper under opprettelse av pools. Per i dag er det vel kun HS/Index som kan hente ut grupper for studie/klasse

_Originally posted by @olros in https://github.com/TIHLDE/Lepton/issues/429#issuecomment-1059556919_

**Comment by olros** [comment]
Kunne det vært en idé å fjerne filtreringen i backend som ligger på eksisterende endepunkt?

Kan evt legge til en boolean eller noe lignende på hver gruppe i listen som sier om bruker kan hente ut medlemmer i den (public).
