### ISSUE TITLE
Ikke mulig å opprette/endre nyheter uten forfatter

### ISSUE THREAD

**Issue by Eirsteir** [TIHLDE/Lepton#517]
### What happened?

Etter forfatter av nyheter ble introdusert er det ikke lenger mulig å opprette/endre nyheter uten å legge til en forfatter. Vi vil at dette skal kunne gå an. 

Issue i sentry: https://sentry.io/share/issue/2a1dc69958ea433a971f442a3890f090/

### Which users are seeing the problem?

Superadmins (Index), Admins (HS), Logged in users

### Relevant log output

```shell
ValueError: Cannot assign "''": "News.creator" must be a "User" instance.
```

**Comment by martcl** [comment]
Det er mulig å opprette/endre nyheter uten å legge til en forfatter. Buggen var i frontend og her er en fix https://github.com/TIHLDE/Kvark/pull/446

**Comment by Eirsteir** [comment]
Godt løst! 👍
