### ISSUE TITLE
Feil i badges ervervet beregning

### ISSUE THREAD

**Issue by martcl** [TIHLDE/Lepton#519]
### What happened?

Det er totalt 6 medlemmer og bare en av brukerne har badgen Rickrolled. Badgen sier at den er ervervet av 14.3 % av medlemmene, men (1/6) * 100% = 16.7%. 

Beregningen som ble gjort tilsvarer (1/7) * 100% = 14.2%. 

<img width="517" alt="Skjermbilde 2022-03-15 kl  17 07 09" src="https://user-images.githubusercontent.com/26656069/158421133-d1f6f602-4fb2-461c-84b7-39124932134f.png">
<img width="1221" alt="Skjermbilde 2022-03-15 kl  17 06 40" src="https://user-images.githubusercontent.com/26656069/158421158-91ee467f-55ce-458a-bcb4-0a6ca33adea5.png">

### Which users are seeing the problem?

Logged in users

**Comment by olros** [comment]
1/7 kommer fra at det er 7 brukere totalt, men bare 6 av dem er godkjente brukere, altså 1 som venter på godkjenning. Om man vil endre til å bruke godkjente brukere så holder det å endre til count av users i TIHLDE-gruppen
