### ISSUE TITLE
Det skal ikke være mulig å melde seg på når arrangementet har 0 plasser

### ISSUE THREAD

**Issue by Eirsteir** [TIHLDE/Lepton#537]
### What happened?

Her har 4 stk klart å melde seg på når det er 0 plasser på arrangementet
![image](https://user-images.githubusercontent.com/35424810/160409178-3fb5a5c0-a55e-4103-92c1-b7d2b016c0e9.png)

### Which users are seeing the problem?

Superadmins (Index), Admins (HS), Logged in users, Anonymous users

**Comment by olros** [comment]
En kan evt gjøre dette til en feature og si at hvis antall plasser er lik 0 så kan så mange som ønsker det melde seg på. Så kan vi da vise `∞` som antall plasser

**Comment by martcl** [comment]
Dette er gjort i fronted
