### ISSUE TITLE
Skjule maks antall deltagere på arrangementer 

### ISSUE THREAD

**Issue by martcl** [TIHLDE/Lepton#540]
### Feature request

Som event organisator ønsker jeg at flest mulig melder seg på arrangementer. Av og til kan det være nyttig å skjule maks antall tillatte deltagere på et arrangement for å få flere deltagere til å melde seg på. På denne måten vil man også få flere til å melde seg på venteliste.

Forslag:
Legg til et ekstra felt i events modellen som sier om man skal skjule eller vise maks antall deltagere i frontend.

**Comment by martcl** [comment]
Er dette noe vi ønsker å legge til?

**Comment by CJGutz** [comment]
Tenker selv det er unødvendig. Om bare arrangementer med få deltakere bruker denne muligheten, vil problemet fortsatt vedvare.
