### ISSUE TITLE
Endring til færre plasser på arrangement enn påmeldte skaper overflow av påmeldte

### ISSUE THREAD

**Issue by lille-morille** [TIHLDE/Lepton#723]
### What happened?

Lag et arrangement med 10 personer.
Meld på 10 personer.
Endre arrangement til å ha plass til 5 personer.
Det er nå 10/5 personer påmeldt på arrangementet.

Usikker på om dette trengs å fikses hvis det ikke forekommer, men kan være fint å få det kartlagt.

### Which users are seeing the problem?

Admins (HS)

**Comment by MadsNyl** [comment]
Jeg har laget en PR som fikser dette, med å automatisk oppdatere ventelisten

**Comment by MadsNyl** [comment]
Jeg har laget en PR som fikser dette, med å automatisk oppdatere ventelisten
