### ISSUE TITLE
Gjøre det mulig for ledere av undergrupper å søke etter medlemmer

### ISSUE THREAD

**Issue by maxschau** [TIHLDE/Lepton#81]
Ledere av grupper har ikke de samme rettighetene som for eksempel medlemme av Index. Det gjør at disse heller ikke kan søke etter medlemmer. For at de skal kunne legge til medlemmer i gruppen sin må de også kunne søke etter medlemmer.

**Comment by olros** [comment]
Dette er vel fikset? @maxschau @Her0elt

**Comment by Her0elt** [comment]
@olros ja vil nok si det, men kan nok bli gjort på en bedre måte. Per nà så sier vi bare hvis du er leder av en gruppe skan du liste alle brukere

**Comment by olros** [comment]
Tenker vi lukker dette issuet da :)
